services:
  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - tenet
    volumes:
      - redis-data:/data

  db:
    image: postgres:15-alpine
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - tenet
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  tenet:
    external: true

volumes:
  redis-data:
  db-data:
